// =============================================================
// Power BI / DAX
// Random numbers in [1.5, 2.5] + spacing logic
// -------------------------------------------------------------
// HOW TO USE:
// 1) Replace 'Data' with your table name.
// 2) Replace 'Data'[ID] with a unique, stable key.
// 3) (Optional) Replace 'Data'[Group] with your grouping column.
// =============================================================


// -------------------------------------------------------------
// 1) Simple continuous random between 1.5 and 2.5
// -------------------------------------------------------------
'Data'[RandomNumber] =
RAND() + 1.5
// RAND() ∈ [0,1)  → +1.5 → [1.5,2.5)


// -------------------------------------------------------------
// 2) Random with 0.1 step increments (1.5, 1.6, …, 2.5)
// -------------------------------------------------------------
'Data'[RandomStep] =
(RANDBETWEEN(0, 10) * 0.1) + 1.5


// -------------------------------------------------------------
// 3) Deterministic cyclic pattern (global)
// -------------------------------------------------------------
'Data'[GlobalRank] =
RANKX(
    ALL('Data'),
    'Data'[ID],
    ,
    ASC,
    DENSE
)

'Data'[DiscreteValueCyclic] =
VAR idx = MOD('Data'[GlobalRank] - 1, 3) + 1
RETURN
SWITCH(
    idx,
    1, 1.5,
    2, 2.0,
    3, 2.5
)


// -------------------------------------------------------------
// 4) Cyclic pattern per group
// -------------------------------------------------------------
'Data'[RankInGroup] =
VAR g = 'Data'[Group]
RETURN
RANKX(
    FILTER(ALL('Data'), 'Data'[Group] = g),
    'Data'[ID],
    ,
    ASC,
    DENSE
)

'Data'[DiscreteValueCyclicPerGroup] =
VAR idx = MOD('Data'[RankInGroup] - 1, 3) + 1
RETURN
SWITCH(
    idx,
    1, 1.5,
    2, 2.0,
    3, 2.5
)


// -------------------------------------------------------------
// 5) Strict version (only 3 values per group)
// -------------------------------------------------------------
'Data'[AssignedValueUniqueTop3] =
VAR k = 'Data'[RankInGroup]
RETURN
SWITCH(
    TRUE(),
    k = 1, 1.5,
    k = 2, 2.0,
    k = 3, 2.5,
    BLANK()
)


// -------------------------------------------------------------
// Optional tip:
// Create a stable [ID] column (e.g. "Add Index" in Power Query)
// so RANKX results are deterministic.
// -------------------------------------------------------------
